#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$( cd $DIR && cd .. && pwd )"

echo "Installing dotfiles..."

function symlink_oh_my_zsh_theme {
  echo "Symlink the Oh My Zsh theme..."
  # Add ln -i and -v option
  ln -s $REPO_DIR/.oh-my-zsh/themes/jandintel.zsh-theme ~/.oh-my-zsh/themes/jandintel.zsh-theme
}

symlink_oh_my_zsh_theme

echo "Done"
